@endpoint = http://api.dev.smallsaas.cn:8084
@local = http://localhost:8080

### 管理员登陆
POST {{local}}/api/sys/oauth/login

{
    "account": "admin",
    "password": "111111"
}

### 注册
POST {{endpoint}}/api/app/oauth/player/register

{
    "name": "ownTest",
    "phone": "15322315902",
    "verifyCode": "111111",
    "loginPassword": "admin",
    "invitationCode": "PNywB5"
}


### 登陆
POST {{endpoint}}/api/app/oauth/player/login

{
    "account": "15322315902",
    "password": "admin"
}