@endpoint = http://repo.dev.smallsaas.cn:8084
@local = http://localhost:8080
@player1 = Bearer eyJ0eXBlIjoiSldUIiwiYWxnIjoiSFM1MTIifQ.eyJvcmdJZCI6IiIsInVzZXJJZCI6MTQsImFjY291bnQiOiJhY2M5Mjk2NTU4MSIsImRvbWFpblVzZXJJZCI6MTQsImlhdCI6MTY0MDMzNjQ3NiwianRpIjoiMTQiLCJzdWIiOiJhY2M5Mjk2NTU4MSIsImV4cCI6MTY0MDU5NTY3Nn0.mLdfjKHMK3_Bx6pw5DofZSbn05NSP3g_m3yuGYeJ9C3ILkkaauVhxk1fBRwCAPC9SFOnOw7ngfV9RaWM8R2tgg"eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzUxMiJ9.eyJvcmdJZCI6IjEiLCJ1c2VySWQiOiIxIiwidXNlclR5cGUiOjEwMSwiYlVzZXJUeXBlIjoiU1lTVEVNIiwidGVuYW50T3JnSWQiOjEsImFjY291bnQiOiJhZG1pbiIsImV4dHJhVXNlclR5cGUiOjAsImlhdCI6MTY0MDMzMzg0OSwianRpIjoiMSIsInN1YiI6ImFkbWluIiwiZXhwIjoxNjQwNTkzMDQ5fQ.WgpKivw08u4xzge9rWc28ySbueJRQsW8zqXlqGoRgbuPgszT4_qpl0XHoGn9omRRYnj-Psgmfztcoj-636n0pQ
@player1 = Bearer eyJ0eXBlIjoiSldUIiwiYWxnIjoiSFM1MTIifQ.eyJvcmdJZCI6IiIsInVzZXJJZCI6MjIsImFjY291bnQiOiJhY2MxODA3MTc1MyIsImRvbWFpblVzZXJJZCI6MTEsImlhdCI6MTY0MDQxMjk0NCwianRpIjoiMjIiLCJzdWIiOiJhY2MxODA3MTc1MyIsImV4cCI6MTY0MDY3MjE0NH0.tTVCuz9XYlhBFVNLYZ44-mlnfuKf5V4DlQr53G4FxWBfqjCvmG64TQr4QZrJ8Clki_iz_afhdjlAfhcpfNLPlQ

### 玩家注册
POST {{local}}/api/app/oauth/account/register

{
  "phone": "18664521094",
  "password": "123456"
}
### 玩家登录
POST {{local}}/api/app/oauth/account/login

{
  "account": "18664521094",
  "password": "123456"
}







### 查看玩家资源
GET {{local}}/api/u/player/wallet
Authorization: {{player1}}


### 精灵市场列表
GET {{local}}/api/u/wisp/market
Authorization: {{player1}}


### 购买陪伴精灵
//陪伴精灵需大于所需陪伴精灵才能购买
POST {{local}}/api/u/companionWisp/2/buy
Authorization: {{player1}}

{
  "companionWispId": 1,
  "number": 1,
  "paymentPassword": "123456"
}


### 查看陪伴精灵
GET {{local}}/api/crud/oms/companionWisp/companionWisps
Authorization: {{player1}}

### 租用土地
POST {{local}}/api/u/land/1/buy
Authorization: {{player1}}

{
  "paymentPassword": "123456",
  "purchaseQuantity": 10
}

### 查看玩家资源
GET {{local}}/api/u/player/wallet
Authorization: {{player1}}

### 预约精灵
POST {{local}}/api/u/wisp/1/book
Authorization: {{player1}}

{
  "paymentPassword": "123456"
}




### 查看预约精灵记录
GET {{endpoint}}/api/crud/oms/wispBookingRecord/wispBookingRecords
Authorization: {{player1}}



### 精灵市场列表
GET {{endpoint}}/api/crud/oms/wisp/wisps/market
Authorization: {{player1}}



### 查看元精灵详情
GET {{local}}/api/crud/oms/wispMeta/wispMetas/1
Authorization: {{player1}}



### 查看元精灵
GET {{local}}/api/crud/oms/wispMeta/wispMetas
Authorization: {{player1}}


###
GET {{local}}/api/u/player
Authorization: {{player1}}
